### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by dyxwxjdy** [The-SS/quadrotor_trajectory#1]
Hi SS,
         I just ran the demo without any other edit, but met this problem:

>   File "quadrotor_trajectory/scripts/min_snap_traj.py", line 436, in <module>
>     st.traj_stepwise(w)
>   File "quadrotor_trajectory/scripts/min_snap_traj.py", line 178, in traj_stepwise
>     x_v = np.array(self.min_snap(0.0, tf[0]-ti[0], xi, xf))
>   File "quadrotor_trajectory/scripts/min_snap_traj.py", line 280, in min_snap
>     return np.array(V.value)[:,0]
> IndexError: too many indices for array

         is this related with numpy version? 

Thanks

**Comment by The-SS** [comment]
I am using Python 2.7. I have cvxpy version 0.4.9 installed using Anaconda. The demo runs properly on MacOS.

What version of Python and CVXPy are you using?
Have you made any modifications to the code or demo?
Also, try printing `np.array(V.value)` before the return statement. For the 7-degree polynomial, you should get an 8x1 matrix. e.g. `
[[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]]`.
`np.array(V.value)[:,0]` takes the first column of the matrix and groups them into a 1x8 vector. e.g. `[0 0 0 0 0 0 0 0]`

**Comment by The-SS** [comment]
@dyxwxjdy Any update? Were you able to resolve the issue?

**Comment by dyxwxjdy** [comment]
@The-SS Really sorry for late reply.  It`s solved by updating cvxpy. Thank you very much!
